server:
  port: 8083
  servlet:
    # Tutte le chiamate saranno hostname:port/post
    context-path: /object

spring:
  config:
    activate:
      on-profile: object
  application:
    name: msobject


app:
  name: object
  items: car, dog, soccer, music, painting, mathematics, biology, geography, language, poetry, cooking, hiking, wildlife, cinema, ballet, photography, technology, fashion, wellness, yoga
