#YAML WORD
server:
  port: 8081
  servlet:
    # Tutte le chiamate saranno hostname:port/post
    context-path: /subject

spring:
  config:
    activate:
      on-profile: subject
  application:
    name: mssubject

app:
  name: subject
  items: sub1,sub2,sub3,sub4,sub5



server:
  port: 8082
  servlet:
    # Tutte le chiamate saranno hostname:port/verb
    context-path: /verb

spring:
  config:
    activate:
      on-profile: verb
  application:
    name: msverb


app:
  name: verb
  items: verb1,verb2,verb3,verb4,verb5


server:
  port: 8083
  servlet:
    # Tutte le chiamate saranno hostname:port/post
    context-path: /object

spring:
  config:
    activate:
      on-profile: object
  application:
    name: msobject


app:
  name: object
  items: obj1,obj2,obj3,obj4,obj5
