server:
  port: 8082
  servlet:
    # Tutte le chiamate saranno hostname:port/verb
    context-path: /verb

spring:
  config:
    activate:
      on-profile: verb
  application:
    name: msverb


app:
  name: verb
  items: likes, sees, eats, paints, cooks, writes, reads, codes, admires, explores, understands, cleans, photographs, washes, prepares, creates, inspires, motivates, describes, draws
