server:
  port: 8081
  servlet:
    # Tutte le chiamate saranno hostname:port/post
    context-path: /subject

spring:
  config:
    activate:
      on-profile: subject
  application:
    name: mssubject

app:
  name: subject
  items: dog, cat, sport, music, portrait, table, book, water, banana, fly, food, bird, sun, film, spoon, phone, jacket, tree, bottle, TV
