server:
  port: 8081
  servlet:
    # Tutte le chiamate saranno hostname:port/post
    context-path: /subject

spring:
  config:
    activate:
      on-profile: subject
  application:
    name: mssubject

app:
  name: subject
  items: sub1,sub2,sub3,sub4,sub5
